name: DEFRAGMO
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.2.1
  - cryptography=41.0.7
  - cuda-cccl=12.3.101=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=11.8.0=0
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.1
  - freetype=2.12.1
  - gmpy2=2.1.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.1
  - ipython=8.21.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - lerc=3.0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.4.107=0
  - libcurand-dev=10.3.4.107=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown=3.5.2
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.2
  - pandas=2.1.4
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=4.2.0
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - werkzeug=3.0.1
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.48.1
      - gensim==4.3.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
#      - mol2vec==0.1
      - prompt-toolkit==3.0.43
      - protobuf==4.25.2
      - pyparsing==3.1.1
      - rdkit==2023.9.4
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - smart-open==6.4.0
      - stack-data==0.6.3
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - torchaudio==2.2.0
      - torchvision==0.17.0